### ISSUE TITLE
automated tests in supported browsers

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer_elements#48] opened 2015-08-19 16:11 UTC
I noticed when working on a web component using the new elements that they don't necessarily work when run in browsers other than Dartium.  Chrome and Firefox are better than Safari. Given that the end target is javascript, seems reasonable that these should be tested against other browsers in javascript form.  

A reasonable start might be to setup automated tests on drone.io for webkit based browsers and Chrome, but that would leave out IE, Edge and Safari.  [Browserstack](http://www.browserstack.com) might be a better option.  I'm not sure if there's a free for open source option available anywhere.

**Comment by jakemac53** [comment] 2015-08-19 18:13
duplicate of https://github.com/dart-lang/polymer_elements/issues/10

**Closed as completed by jakemac53** 2015-08-19 18:13 UTC
Labels: duplicate

**Comment by jakemac53** [comment] 2015-08-19 18:15
fwiw, we have some internal infrastructure for this, its not ideal (doesn't give status in pull requests, and is not visible at all to external contributers afaik) but it does have good browser coverage and is relatively easy to set up. That is probably what I will go with, at least to start things off.
